version: '3'
services:
  app:
    build: Docker-app/
    container_name: devopsapp
    ports: 
      - "8081:8080"
    depends_on:
      - db
  db: 
    build: Docker-db/
    container_name: devopsdb
    ports:
      - "8082:3306"
